include ../default_targets.h

test: 
	make -e DOCK_VERBOSE='-v' flex1.dockout flex2.dockout flex3.dockout flex4.dockout flex5.dockout fad6_growthtree.dockout

clean: clean_dock
	/bin/rm -f LIG1_anchor1_branch*.mol2
