/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /usr/local/cvsroot/dock6/docs/faq/lex.mm_options.c,v 1.1 2006/11/08 19:30:23 sbrozell Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define mmoconst const
#else
#define mmoconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN mmo_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((mmo_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE mmorestart( mmoin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct mmo_buffer_state *YY_BUFFER_STATE;

extern int mmoleng;
extern FILE *mmoin, *mmoout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		mmoless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the mmoless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define mmoless(n) \
	do \
		{ \
		/* Undo effects of setting up mmotext. */ \
		*mmo_cp = mmo_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		mmo_c_buf_p = mmo_cp = mmo_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up mmotext again */ \
		} \
	while ( 0 )

#define unput(c) mmounput( c, mmotext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int mmo_size_t;


struct mmo_buffer_state
	{
	FILE *mmo_input_file;

	char *mmo_ch_buf;		/* input buffer */
	char *mmo_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	mmo_size_t mmo_buf_size;

	/* Number of characters read into mmo_ch_buf, not including EOB
	 * characters.
	 */
	int mmo_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int mmo_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int mmo_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int mmo_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int mmo_fill_buffer;

	int mmo_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via mmorestart()), so that the user can continue scanning by
	 * just pointing mmoin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE mmo_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER mmo_current_buffer


/* mmo_hold_char holds the character lost when mmotext is formed. */
static char mmo_hold_char;

static int mmo_n_chars;		/* number of characters read into mmo_ch_buf */


int mmoleng;

/* Points to current character in buffer. */
static char *mmo_c_buf_p = (char *) 0;
static int mmo_init = 1;		/* whether we need to initialize */
static int mmo_start = 0;	/* start state number */

/* Flag which is used to allow mmowrap()'s to do buffer switches
 * instead of setting up a fresh mmoin.  A bit of a hack ...
 */
static int mmo_did_buffer_switch_on_eof;

void mmorestart YY_PROTO(( FILE *input_file ));

void mmo_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void mmo_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE mmo_create_buffer YY_PROTO(( FILE *file, int size ));
void mmo_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void mmo_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void mmo_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER mmo_flush_buffer( mmo_current_buffer )

YY_BUFFER_STATE mmo_scan_buffer YY_PROTO(( char *base, mmo_size_t size ));
YY_BUFFER_STATE mmo_scan_string YY_PROTO(( mmoconst char *mmo_str ));
YY_BUFFER_STATE mmo_scan_bytes YY_PROTO(( mmoconst char *bytes, int len ));

static void *mmo_flex_alloc YY_PROTO(( mmo_size_t ));
static void *mmo_flex_realloc YY_PROTO(( void *, mmo_size_t ));
static void mmo_flex_free YY_PROTO(( void * ));

#define mmo_new_buffer mmo_create_buffer

#define mmo_set_interactive(is_interactive) \
	{ \
	if ( ! mmo_current_buffer ) \
		mmo_current_buffer = mmo_create_buffer( mmoin, YY_BUF_SIZE ); \
	mmo_current_buffer->mmo_is_interactive = is_interactive; \
	}

#define mmo_set_bol(at_bol) \
	{ \
	if ( ! mmo_current_buffer ) \
		mmo_current_buffer = mmo_create_buffer( mmoin, YY_BUF_SIZE ); \
	mmo_current_buffer->mmo_at_bol = at_bol; \
	}

#define YY_AT_BOL() (mmo_current_buffer->mmo_at_bol)

typedef unsigned char YY_CHAR;
FILE *mmoin = (FILE *) 0, *mmoout = (FILE *) 0;
typedef int mmo_state_type;
extern char *mmotext;
#define mmotext_ptr mmotext

static mmo_state_type mmo_get_previous_state YY_PROTO(( void ));
static mmo_state_type mmo_try_NUL_trans YY_PROTO(( mmo_state_type current_state ));
static int mmo_get_next_buffer YY_PROTO(( void ));
static void mmo_fatal_error YY_PROTO(( mmoconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up mmotext.
 */
#define YY_DO_BEFORE_ACTION \
	mmotext_ptr = mmo_bp; \
	mmoleng = (int) (mmo_cp - mmo_bp); \
	mmo_hold_char = *mmo_cp; \
	*mmo_cp = '\0'; \
	mmo_c_buf_p = mmo_cp;

#define YY_NUM_RULES 42
#define YY_END_OF_BUFFER 43
static mmoconst short int mmo_accept[219] =
    {   0,
        0,    0,   43,   41,   40,   40,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   40,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   10,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    0,    0,    0,
       21,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    1,    0,    0,   31,    0,    0,    0,    0,
        0,    0,    0,   20,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   37,   36,    0,    0,    0,    0,    0,
        0,    0,   30,    0,    0,    7,    0,    0,    5,    4,
        0,    6,    0,    0,    3,    2,    0,    0,    0,    0,
        0,    0,    0,    0,   35,    0,   38,    0,    0,    0,
        0,    0,    0,   27,    8,    0,    0,    0,    0,    0,
       11,   12,   13,    0,   17,   19,   33,    0,    0,    0,
       26,    0,    0,    0,    0,    0,    0,   39,   28,    0,

       14,   34,    0,   25,    0,    0,    0,   16,    0,   18,
       29,   32,   15,    0,   22,   23,   24,    0
    } ;

static mmoconst int mmo_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    2,    5,    5,    1,    6,    7,    8,
        9,   10,   11,   12,   12,   12,   13,    1,    1,    1,
       14,    1,    1,    1,    1,    1,   15,    1,    5,    1,
        1,    1,    1,    1,    1,   16,    1,    1,    1,    1,
        1,   17,    1,    1,    1,    1,    1,    1,   18,    1,
        1,    1,    1,    1,   19,    1,   20,   21,   22,   23,

       24,   25,   26,   27,   28,    1,   29,   30,   31,   32,
       33,   34,    1,   35,   36,   37,   38,   39,   40,   41,
        1,   42,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static mmoconst int mmo_meta[43] =
    {   0,
        1,    1,    1,    1,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1
    } ;

static mmoconst short int mmo_base[245] =
    {   0,
        0,   41,  304,  305,    3,    6,  265,   10,    0,    7,
        1,   19,   26,   11,   55,  272,  279,  276,   10,  262,
       26,   11,  275,  261,  265,   78,  263,  271,  259,  265,
      272,  258,   26,  252,  267,   29,  252,    0,  248,  254,
      256,  250,  247,   16,  251,   44,    0,  256,  255,  247,
       82,  258,  253,  255,  243,   58,  239,  243,  248,  249,
      234,  227,  230,  235,  241,  243,  238,    0,  225,  227,
      229,  227,  225,    0,   80,    7,    0,  236,  215,  235,
      305,  231,  229,   81,  232,    0,  231,   92,  226,   87,
       94,   95,  219,  228,  101,  103,  210,  212,   97,  217,

      208,  204,    0,  101,  106,  305,  204,  204,  221,  215,
      217,  105,  201,    0,  117,    0,  118,  215,    0,    0,
      204,    0,  210,  192,    0,    0,  208,  119,  120,  122,
      194,  123,  124,  305,   55,  210,    0,  203,  125,  198,
      206,  188,  305,  189,    0,    0,    0,  186,    0,    0,
      200,    0,  126,  131,    0,    0,  190,    0,    0,    0,
      137,    0,    0,  211,  207,  188,    0,  138,    0,  186,
      179,  190,  139,    0,    0,  189,  140,  140,    0,  144,
        0,    0,    0,    0,    0,    0,  305,  204,  182,  143,
        0,  151,  186,  152,    0,  153,    0,  305,    0,    0,

        0,  305,  177,  305,    0,  155,  154,    0,  156,    0,
        0,  305,    0,  164,  305,  305,  305,  305,  171,  173,
      175,  177,  179,  165,  161,  101,   84,  181,  183,  185,
      187,   71,  189,  191,  193,  195,   48,  197,  199,  201,
      203,   15,  205,  207
    } ;

static mmoconst short int mmo_def[245] =
    {   0,
      219,  219,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  220,  218,  218,
      218,  218,  218,  218,  218,  218,  221,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  220,  218,  218,
      218,  218,  218,  222,  218,  218,  221,  218,  218,  218,
      218,  218,  218,  218,  218,  223,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,

      218,  218,  222,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  223,  218,  224,  218,  218,  225,  226,
      218,  227,  218,  218,  228,  229,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  230,  218,  218,  218,
      218,  218,  218,  218,  231,  224,  232,  218,  225,  226,
      218,  227,  218,  218,  228,  229,  218,  233,  234,  235,
      218,  236,  237,  218,  218,  218,  230,  218,  238,  218,
      218,  218,  218,  231,  232,  218,  218,  218,  239,  218,
      233,  234,  235,  240,  236,  237,  218,  218,  218,  218,
      238,  218,  218,  218,  241,  218,  242,  218,  239,  243,

      240,  218,  218,  218,  244,  218,  218,  241,  218,  242,
      243,  218,  244,  218,  218,  218,  218,    0,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218
    } ;

static mmoconst short int mmo_nxt[348] =
    {   0,
      218,    5,    6,    5,   19,   19,   19,   19,   19,   19,
       28,   19,   19,   19,   47,  106,  106,  210,   23,   74,
       29,    7,    8,    9,   47,   10,   25,   26,   11,   74,
       27,   12,   36,   24,   13,   14,   15,   21,   16,   17,
       30,   18,    5,    6,    5,   34,   22,   76,   37,   45,
      186,   35,   65,   31,   32,   33,   46,   76,   38,   61,
       66,   86,    7,    8,    9,   62,   10,  164,   38,   11,
      165,   86,   12,  175,   39,   13,   14,   15,   40,   16,
       17,   51,   18,  104,  112,   52,  152,   81,   81,   81,
      119,   51,   81,  104,  112,  116,   53,  120,  122,  117,

      119,  105,  129,  150,  125,  116,  126,  120,  122,  137,
      143,  143,  121,   54,  125,  134,  126,  135,  136,  137,
      145,  147,  158,  159,  130,  160,  162,  163,  169,  178,
      145,  147,  158,  159,  179,  160,  162,  163,  169,  178,
      184,  190,  195,  197,  179,  198,  198,  200,  204,  204,
      184,  190,  195,  197,  205,  207,  209,  200,  214,  215,
      215,  216,  216,  149,  205,  207,  209,  146,  214,  217,
      217,    4,    4,    4,   68,   68,   77,   77,  103,  103,
      114,  114,  155,  155,  156,  156,  167,  167,  174,  174,
      181,  181,  182,  182,  183,  183,  185,  185,  191,  191,

      199,  199,  201,  201,  208,  208,  211,  211,  213,  213,
      212,  206,  203,  202,  196,  194,  193,  192,  189,  188,
      187,  180,  177,  176,  173,  172,  171,  170,  168,  166,
      161,  157,  154,  153,  151,  148,  144,  142,  141,  140,
      139,  138,  133,  132,  131,  128,  127,  124,  123,  118,
      115,  113,  111,  110,  109,  108,  107,  102,  101,  100,
       99,   98,   97,   96,   95,   94,   93,   92,   91,   90,
       89,   88,   87,   85,   84,   83,   82,   80,   79,   78,
       75,   73,   72,   71,   70,   69,   67,   64,   63,   60,
       59,   58,   57,   56,   55,   50,   49,   48,   44,   43,

       42,   41,   20,  218,    3,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218
    } ;

static mmoconst short int mmo_chk[348] =
    {   0,
        0,    1,    1,    1,    5,    5,    5,    6,    6,    6,
       11,   19,   19,   19,   22,   76,   76,  242,    9,   44,
       11,    1,    1,    1,   22,    1,   10,   10,    1,   44,
       10,    1,   14,    9,    1,    1,    1,    8,    1,    1,
       12,    1,    2,    2,    2,   13,    8,   46,   14,   21,
      237,   13,   36,   12,   12,   12,   21,   46,   15,   33,
       36,   56,    2,    2,    2,   33,    2,  135,   15,    2,
      135,   56,    2,  232,   15,    2,    2,    2,   15,    2,
        2,   26,    2,   75,   84,   26,  227,   51,   51,   51,
       90,   26,   51,   75,   84,   88,   26,   91,   92,   88,

       90,   75,   99,  226,   95,   88,   96,   91,   92,  105,
      112,  112,   91,   26,   95,  104,   96,  104,  104,  105,
      115,  117,  128,  129,   99,  130,  132,  133,  139,  153,
      115,  117,  128,  129,  154,  130,  132,  133,  139,  153,
      161,  168,  173,  177,  154,  178,  178,  180,  190,  190,
      161,  168,  173,  177,  192,  194,  196,  180,  206,  207,
      207,  209,  209,  225,  192,  194,  196,  224,  206,  214,
      214,  219,  219,  219,  220,  220,  221,  221,  222,  222,
      223,  223,  228,  228,  229,  229,  230,  230,  231,  231,
      233,  233,  234,  234,  235,  235,  236,  236,  238,  238,

      239,  239,  240,  240,  241,  241,  243,  243,  244,  244,
      203,  193,  189,  188,  176,  172,  171,  170,  166,  165,
      164,  157,  151,  148,  144,  142,  141,  140,  138,  136,
      131,  127,  124,  123,  121,  118,  113,  111,  110,  109,
      108,  107,  102,  101,  100,   98,   97,   94,   93,   89,
       87,   85,   83,   82,   80,   79,   78,   73,   72,   71,
       70,   69,   67,   66,   65,   64,   63,   62,   61,   60,
       59,   58,   57,   55,   54,   53,   52,   50,   49,   48,
       45,   43,   42,   41,   40,   39,   37,   35,   34,   32,
       31,   30,   29,   28,   27,   25,   24,   23,   20,   18,

       17,   16,    7,    3,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  218,  218,  218,  218,  218
    } ;

static mmo_state_type mmo_last_accepting_state;
static char *mmo_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define mmomore() mmomore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *mmotext;
#line 1 "mm_options.l"
#define INITIAL 0
#line 2 "mm_options.l"
extern int mytaskid;

#ifdef flex

#undef YY_INPUT
#define YY_INPUT(b, r, ms) (r = mmo_mmoinput(b, ms))

#else

#undef input
#undef unput
#define input() (*gopts++)
#define unput(c) (*--gopts = c)

#endif

#undef ECHO
#define ECHO if(mytaskid==0)fprintf(mmoout, "\tmm_options:  %s\n",mmotext)


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int mmowrap YY_PROTO(( void ));
#else
extern int mmowrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void mmounput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef mmotext_ptr
static void mmo_flex_strncpy YY_PROTO(( char *, mmoconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int mmo_flex_strlen YY_PROTO(( mmoconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int mmoinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int mmo_start_stack_ptr = 0;
static int mmo_start_stack_depth = 0;
static int *mmo_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void mmo_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void mmo_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int mmo_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( mmotext, mmoleng, 1, mmoout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( mmo_current_buffer->mmo_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( mmoin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( mmoin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, mmoin )) == 0) \
		  && ferror( mmoin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "mmoterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef mmoterminate
#define mmoterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) mmo_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int mmolex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after mmotext and mmoleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register mmo_state_type mmo_current_state;
	register char *mmo_cp = NULL, *mmo_bp = NULL;
	register int mmo_act;

#line 22 "mm_options.l"



	if ( mmo_init )
		{
		mmo_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! mmo_start )
			mmo_start = 1;	/* first start state */

		if ( ! mmoin )
			mmoin = stdin;

		if ( ! mmoout )
			mmoout = stdout;

		if ( ! mmo_current_buffer )
			mmo_current_buffer =
				mmo_create_buffer( mmoin, YY_BUF_SIZE );

		mmo_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		mmo_cp = mmo_c_buf_p;

		/* Support of mmotext. */
		*mmo_cp = mmo_hold_char;

		/* mmo_bp points to the position in mmo_ch_buf of the start of
		 * the current run.
		 */
		mmo_bp = mmo_cp;

		mmo_current_state = mmo_start;
mmo_match:
		do
			{
			register YY_CHAR mmo_c = mmo_ec[YY_SC_TO_UI(*mmo_cp)];
			if ( mmo_accept[mmo_current_state] )
				{
				mmo_last_accepting_state = mmo_current_state;
				mmo_last_accepting_cpos = mmo_cp;
				}
			while ( mmo_chk[mmo_base[mmo_current_state] + mmo_c] != mmo_current_state )
				{
				mmo_current_state = (int) mmo_def[mmo_current_state];
				if ( mmo_current_state >= 219 )
					mmo_c = mmo_meta[(unsigned int) mmo_c];
				}
			mmo_current_state = mmo_nxt[mmo_base[mmo_current_state] + (unsigned int) mmo_c];
			++mmo_cp;
			}
		while ( mmo_base[mmo_current_state] != 305 );

mmo_find_action:
		mmo_act = mmo_accept[mmo_current_state];
		if ( mmo_act == 0 )
			{ /* have to back up */
			mmo_cp = mmo_last_accepting_cpos;
			mmo_current_state = mmo_last_accepting_state;
			mmo_act = mmo_accept[mmo_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( mmo_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*mmo_cp = mmo_hold_char;
			mmo_cp = mmo_last_accepting_cpos;
			mmo_current_state = mmo_last_accepting_state;
			goto mmo_find_action;

case 1:
YY_RULE_SETUP
#line 24 "mm_options.l"
{ ECHO; cut  = atof( &mmotext[4] ); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 25 "mm_options.l"
{ ECHO; scnb = atof( &mmotext[5] ); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "mm_options.l"
{ ECHO; scee = atof( &mmotext[5] ); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 27 "mm_options.l"
{ ECHO; ntpr = atoi(&mmotext[5]) < 1 ? 1 : atoi(&mmotext[5]); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 28 "mm_options.l"
{ ECHO; nsnb = atoi( &mmotext[5] ); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "mm_options.l"
{ ECHO; ntwx = atoi( &mmotext[5] ); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 30 "mm_options.l"
{ ECHO; nchk = atoi( &mmotext[5] ); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 31 "mm_options.l"
{ ECHO; nchk2 = atoi( &mmotext[6] ); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 33 "mm_options.l"
{ ECHO; dt  = atof( &mmotext[3] ); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 34 "mm_options.l"
{ ECHO; t = atof( &mmotext[2] ); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 35 "mm_options.l"
{ ECHO; tautp = atof( &mmotext[6] ); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 "mm_options.l"
{ ECHO; temp0 = atof( &mmotext[6] ); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 37 "mm_options.l"
{ ECHO; tempi = atof( &mmotext[6] ); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 38 "mm_options.l"
{ ECHO; vlimit = atof( &mmotext[7] ); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 39 "mm_options.l"
{ ECHO; gamma_ln = atof( &mmotext[9] ); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 40 "mm_options.l"
{ ECHO; genmass = atof( &mmotext[8] ); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 41 "mm_options.l"
{ ECHO; wcons = atof( &mmotext[6] ); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 42 "mm_options.l"
{ ECHO; ntpr_md = atoi(&mmotext[8]) < 1 ? 1 : atoi(&mmotext[8]); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 43 "mm_options.l"
{ ECHO; zerov = atoi( &mmotext[6] ); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 44 "mm_options.l"
{ ECHO; k4d  = atof( &mmotext[4] ); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 46 "mm_options.l"
{ ECHO; gb = atoi( &mmotext[3] ); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 47 "mm_options.l"
{ ECHO; gb_debug = atoi( &mmotext[9] ); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 48 "mm_options.l"
{ ECHO; nr_debug = atoi( &mmotext[9] ); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 49 "mm_options.l"
{ ECHO; gb2_debug = atoi( &mmotext[10] ); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 50 "mm_options.l"
{ ECHO; e_debug = atoi( &mmotext[8] ); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 51 "mm_options.l"
{ ECHO; epsext = atof( &mmotext[7] ); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 52 "mm_options.l"
{ ECHO; kappa = atof( &mmotext[6] ); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 53 "mm_options.l"
{ ECHO; rgbmax = atof( &mmotext[7] ); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 55 "mm_options.l"
{ ECHO; surften = atof( &mmotext[8] ); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 56 "mm_options.l"
{ ECHO; gbsa = atoi( &mmotext[5] ); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 57 "mm_options.l"
{ ECHO; dim = atoi( &mmotext[4] ); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "mm_options.l"
{ ECHO; dield = -5; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "mm_options.l"
{ ECHO; dield = -4; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "mm_options.l"
{ ECHO; dield = -3; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "mm_options.l"
{ ECHO; dield = -2; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "mm_options.l"
{ ECHO; dield =  0; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "mm_options.l"
{ ECHO; dield =  1; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 65 "mm_options.l"
{ ECHO; dielc = atof( &mmotext[6] ); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "mm_options.l"
{ ECHO; irattle = atoi( &mmotext[7] ); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 69 "mm_options.l"
;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 71 "mm_options.l"
{	
#ifdef flex
                if(mytaskid==0)fprintf( stderr, "Error: unknown mm_option:\n" );
		if(mytaskid==0)fprintf( stderr, "  first character of the option is '%s'.\n", mmotext );
#else
		if(mytaskid==0)fprintf( stderr, "Error unknown mm_option: %s\n", --gopts );
#endif

		exit( 1 );
	}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "mm_options.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	mmoterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int mmo_amount_of_matched_text = (int) (mmo_cp - mmotext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*mmo_cp = mmo_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( mmo_current_buffer->mmo_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed mmoin at a new source and called
			 * mmolex().  If so, then we have to assure
			 * consistency between mmo_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			mmo_n_chars = mmo_current_buffer->mmo_n_chars;
			mmo_current_buffer->mmo_input_file = mmoin;
			mmo_current_buffer->mmo_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for mmo_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since mmo_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( mmo_c_buf_p <= &mmo_current_buffer->mmo_ch_buf[mmo_n_chars] )
			{ /* This was really a NUL. */
			mmo_state_type mmo_next_state;

			mmo_c_buf_p = mmotext_ptr + mmo_amount_of_matched_text;

			mmo_current_state = mmo_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * mmo_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			mmo_next_state = mmo_try_NUL_trans( mmo_current_state );

			mmo_bp = mmotext_ptr + YY_MORE_ADJ;

			if ( mmo_next_state )
				{
				/* Consume the NUL. */
				mmo_cp = ++mmo_c_buf_p;
				mmo_current_state = mmo_next_state;
				goto mmo_match;
				}

			else
				{
				mmo_cp = mmo_c_buf_p;
				goto mmo_find_action;
				}
			}

		else switch ( mmo_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				mmo_did_buffer_switch_on_eof = 0;

				if ( mmowrap() )
					{
					/* Note: because we've taken care in
					 * mmo_get_next_buffer() to have set up
					 * mmotext, we can now set up
					 * mmo_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					mmo_c_buf_p = mmotext_ptr + YY_MORE_ADJ;

					mmo_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! mmo_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				mmo_c_buf_p =
					mmotext_ptr + mmo_amount_of_matched_text;

				mmo_current_state = mmo_get_previous_state();

				mmo_cp = mmo_c_buf_p;
				mmo_bp = mmotext_ptr + YY_MORE_ADJ;
				goto mmo_match;

			case EOB_ACT_LAST_MATCH:
				mmo_c_buf_p =
				&mmo_current_buffer->mmo_ch_buf[mmo_n_chars];

				mmo_current_state = mmo_get_previous_state();

				mmo_cp = mmo_c_buf_p;
				mmo_bp = mmotext_ptr + YY_MORE_ADJ;
				goto mmo_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of mmolex */


/* mmo_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int mmo_get_next_buffer()
	{
	register char *dest = mmo_current_buffer->mmo_ch_buf;
	register char *source = mmotext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( mmo_c_buf_p > &mmo_current_buffer->mmo_ch_buf[mmo_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( mmo_current_buffer->mmo_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( mmo_c_buf_p - mmotext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (mmo_c_buf_p - mmotext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( mmo_current_buffer->mmo_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		mmo_current_buffer->mmo_n_chars = mmo_n_chars = 0;

	else
		{
		int num_to_read =
			mmo_current_buffer->mmo_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = mmo_current_buffer;

			int mmo_c_buf_p_offset =
				(int) (mmo_c_buf_p - b->mmo_ch_buf);

			if ( b->mmo_is_our_buffer )
				{
				int new_size = b->mmo_buf_size * 2;

				if ( new_size <= 0 )
					b->mmo_buf_size += b->mmo_buf_size / 8;
				else
					b->mmo_buf_size *= 2;

				b->mmo_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					mmo_flex_realloc( (void *) b->mmo_ch_buf,
							 b->mmo_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->mmo_ch_buf = 0;

			if ( ! b->mmo_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			mmo_c_buf_p = &b->mmo_ch_buf[mmo_c_buf_p_offset];

			num_to_read = mmo_current_buffer->mmo_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&mmo_current_buffer->mmo_ch_buf[number_to_move]),
			mmo_n_chars, num_to_read );

		mmo_current_buffer->mmo_n_chars = mmo_n_chars;
		}

	if ( mmo_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			mmorestart( mmoin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			mmo_current_buffer->mmo_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	mmo_n_chars += number_to_move;
	mmo_current_buffer->mmo_ch_buf[mmo_n_chars] = YY_END_OF_BUFFER_CHAR;
	mmo_current_buffer->mmo_ch_buf[mmo_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	mmotext_ptr = &mmo_current_buffer->mmo_ch_buf[0];

	return ret_val;
	}


/* mmo_get_previous_state - get the state just before the EOB char was reached */

static mmo_state_type mmo_get_previous_state()
	{
	register mmo_state_type mmo_current_state;
	register char *mmo_cp;

	mmo_current_state = mmo_start;

	for ( mmo_cp = mmotext_ptr + YY_MORE_ADJ; mmo_cp < mmo_c_buf_p; ++mmo_cp )
		{
		register YY_CHAR mmo_c = (*mmo_cp ? mmo_ec[YY_SC_TO_UI(*mmo_cp)] : 1);
		if ( mmo_accept[mmo_current_state] )
			{
			mmo_last_accepting_state = mmo_current_state;
			mmo_last_accepting_cpos = mmo_cp;
			}
		while ( mmo_chk[mmo_base[mmo_current_state] + mmo_c] != mmo_current_state )
			{
			mmo_current_state = (int) mmo_def[mmo_current_state];
			if ( mmo_current_state >= 219 )
				mmo_c = mmo_meta[(unsigned int) mmo_c];
			}
		mmo_current_state = mmo_nxt[mmo_base[mmo_current_state] + (unsigned int) mmo_c];
		}

	return mmo_current_state;
	}


/* mmo_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = mmo_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static mmo_state_type mmo_try_NUL_trans( mmo_state_type mmo_current_state )
#else
static mmo_state_type mmo_try_NUL_trans( mmo_current_state )
mmo_state_type mmo_current_state;
#endif
	{
	register int mmo_is_jam;
	register char *mmo_cp = mmo_c_buf_p;

	register YY_CHAR mmo_c = 1;
	if ( mmo_accept[mmo_current_state] )
		{
		mmo_last_accepting_state = mmo_current_state;
		mmo_last_accepting_cpos = mmo_cp;
		}
	while ( mmo_chk[mmo_base[mmo_current_state] + mmo_c] != mmo_current_state )
		{
		mmo_current_state = (int) mmo_def[mmo_current_state];
		if ( mmo_current_state >= 219 )
			mmo_c = mmo_meta[(unsigned int) mmo_c];
		}
	mmo_current_state = mmo_nxt[mmo_base[mmo_current_state] + (unsigned int) mmo_c];
	mmo_is_jam = (mmo_current_state == 218);

	return mmo_is_jam ? 0 : mmo_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void mmounput( int c, register char *mmo_bp )
#else
static void mmounput( c, mmo_bp )
int c;
register char *mmo_bp;
#endif
	{
	register char *mmo_cp = mmo_c_buf_p;

	/* undo effects of setting up mmotext */
	*mmo_cp = mmo_hold_char;

	if ( mmo_cp < mmo_current_buffer->mmo_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = mmo_n_chars + 2;
		register char *dest = &mmo_current_buffer->mmo_ch_buf[
					mmo_current_buffer->mmo_buf_size + 2];
		register char *source =
				&mmo_current_buffer->mmo_ch_buf[number_to_move];

		while ( source > mmo_current_buffer->mmo_ch_buf )
			*--dest = *--source;

		mmo_cp += (int) (dest - source);
		mmo_bp += (int) (dest - source);
		mmo_current_buffer->mmo_n_chars =
			mmo_n_chars = mmo_current_buffer->mmo_buf_size;

		if ( mmo_cp < mmo_current_buffer->mmo_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--mmo_cp = (char) c;


	mmotext_ptr = mmo_bp;
	mmo_hold_char = *mmo_cp;
	mmo_c_buf_p = mmo_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int mmoinput()
#else
static int input()
#endif
	{
	int c;

	*mmo_c_buf_p = mmo_hold_char;

	if ( *mmo_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* mmo_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( mmo_c_buf_p < &mmo_current_buffer->mmo_ch_buf[mmo_n_chars] )
			/* This was really a NUL. */
			*mmo_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = mmo_c_buf_p - mmotext_ptr;
			++mmo_c_buf_p;

			switch ( mmo_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because mmo_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					mmorestart( mmoin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( mmowrap() )
						return EOF;

					if ( ! mmo_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return mmoinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					mmo_c_buf_p = mmotext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) mmo_c_buf_p;	/* cast for 8-bit char's */
	*mmo_c_buf_p = '\0';	/* preserve mmotext */
	mmo_hold_char = *++mmo_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void mmorestart( FILE *input_file )
#else
void mmorestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! mmo_current_buffer )
		mmo_current_buffer = mmo_create_buffer( mmoin, YY_BUF_SIZE );

	mmo_init_buffer( mmo_current_buffer, input_file );
	mmo_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void mmo_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void mmo_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( mmo_current_buffer == new_buffer )
		return;

	if ( mmo_current_buffer )
		{
		/* Flush out information for old buffer. */
		*mmo_c_buf_p = mmo_hold_char;
		mmo_current_buffer->mmo_buf_pos = mmo_c_buf_p;
		mmo_current_buffer->mmo_n_chars = mmo_n_chars;
		}

	mmo_current_buffer = new_buffer;
	mmo_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (mmowrap()) processing, but the only time this flag
	 * is looked at is after mmowrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	mmo_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void mmo_load_buffer_state( void )
#else
void mmo_load_buffer_state()
#endif
	{
	mmo_n_chars = mmo_current_buffer->mmo_n_chars;
	mmotext_ptr = mmo_c_buf_p = mmo_current_buffer->mmo_buf_pos;
	mmoin = mmo_current_buffer->mmo_input_file;
	mmo_hold_char = *mmo_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE mmo_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE mmo_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) mmo_flex_alloc( sizeof( struct mmo_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in mmo_create_buffer()" );

	b->mmo_buf_size = size;

	/* mmo_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->mmo_ch_buf = (char *) mmo_flex_alloc( b->mmo_buf_size + 2 );
	if ( ! b->mmo_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in mmo_create_buffer()" );

	b->mmo_is_our_buffer = 1;

	mmo_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void mmo_delete_buffer( YY_BUFFER_STATE b )
#else
void mmo_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == mmo_current_buffer )
		mmo_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->mmo_is_our_buffer )
		mmo_flex_free( (void *) b->mmo_ch_buf );

	mmo_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void mmo_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void mmo_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	mmo_flush_buffer( b );

	b->mmo_input_file = file;
	b->mmo_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->mmo_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->mmo_is_interactive = 0;
#else
	b->mmo_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void mmo_flush_buffer( YY_BUFFER_STATE b )
#else
void mmo_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->mmo_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->mmo_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->mmo_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->mmo_buf_pos = &b->mmo_ch_buf[0];

	b->mmo_at_bol = 1;
	b->mmo_buffer_status = YY_BUFFER_NEW;

	if ( b == mmo_current_buffer )
		mmo_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE mmo_scan_buffer( char *base, mmo_size_t size )
#else
YY_BUFFER_STATE mmo_scan_buffer( base, size )
char *base;
mmo_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) mmo_flex_alloc( sizeof( struct mmo_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in mmo_scan_buffer()" );

	b->mmo_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->mmo_buf_pos = b->mmo_ch_buf = base;
	b->mmo_is_our_buffer = 0;
	b->mmo_input_file = 0;
	b->mmo_n_chars = b->mmo_buf_size;
	b->mmo_is_interactive = 0;
	b->mmo_at_bol = 1;
	b->mmo_fill_buffer = 0;
	b->mmo_buffer_status = YY_BUFFER_NEW;

	mmo_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE mmo_scan_string( mmoconst char *mmo_str )
#else
YY_BUFFER_STATE mmo_scan_string( mmo_str )
mmoconst char *mmo_str;
#endif
	{
	int len;
	for ( len = 0; mmo_str[len]; ++len )
		;

	return mmo_scan_bytes( mmo_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE mmo_scan_bytes( mmoconst char *bytes, int len )
#else
YY_BUFFER_STATE mmo_scan_bytes( bytes, len )
mmoconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	mmo_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) mmo_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in mmo_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = mmo_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in mmo_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->mmo_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void mmo_push_state( int new_state )
#else
static void mmo_push_state( new_state )
int new_state;
#endif
	{
	if ( mmo_start_stack_ptr >= mmo_start_stack_depth )
		{
		mmo_size_t new_size;

		mmo_start_stack_depth += YY_START_STACK_INCR;
		new_size = mmo_start_stack_depth * sizeof( int );

		if ( ! mmo_start_stack )
			mmo_start_stack = (int *) mmo_flex_alloc( new_size );

		else
			mmo_start_stack = (int *) mmo_flex_realloc(
					(void *) mmo_start_stack, new_size );

		if ( ! mmo_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	mmo_start_stack[mmo_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void mmo_pop_state()
	{
	if ( --mmo_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(mmo_start_stack[mmo_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int mmo_top_state()
	{
	return mmo_start_stack[mmo_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void mmo_fatal_error( mmoconst char msg[] )
#else
static void mmo_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine mmoless() so it works in section 3 code. */

#undef mmoless
#define mmoless(n) \
	do \
		{ \
		/* Undo effects of setting up mmotext. */ \
		mmotext[mmoleng] = mmo_hold_char; \
		mmo_c_buf_p = mmotext + n; \
		mmo_hold_char = *mmo_c_buf_p; \
		*mmo_c_buf_p = '\0'; \
		mmoleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef mmotext_ptr
#ifdef YY_USE_PROTOS
static void mmo_flex_strncpy( char *s1, mmoconst char *s2, int n )
#else
static void mmo_flex_strncpy( s1, s2, n )
char *s1;
mmoconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int mmo_flex_strlen( mmoconst char *s )
#else
static int mmo_flex_strlen( s )
mmoconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *mmo_flex_alloc( mmo_size_t size )
#else
static void *mmo_flex_alloc( size )
mmo_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *mmo_flex_realloc( void *ptr, mmo_size_t size )
#else
static void *mmo_flex_realloc( ptr, size )
void *ptr;
mmo_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void mmo_flex_free( void *ptr )
#else
static void mmo_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	mmolex();
	return 0;
	}
#endif
#line 82 "mm_options.l"


int mmowrap(){
	return( 1 );
}

#ifdef flex


int  mmo_mmoinput( buf, max_size )

char *buf;
int  max_size;
{
	int n;

	if( max_size > &gopts[mmoinputlim] - mmoinputptr ) 
		n =  &gopts[mmoinputlim] - mmoinputptr;
	else
		n = max_size;

	if( n>0 ){
		memcpy( buf, mmoinputptr, n );
		mmoinputptr += n;
	}
	return n;
}

#endif
